# name: Metrics
# on:
#   # Schedule daily updates
#   schedule: [{cron: "0 0 * * *"}]
#   # (optional) Run workflow manually
#   workflow_dispatch:
#   # (optional) Run workflow when pushing on master/main
#   push: {branches: ["master", "main"]}
# jobs:
#   github-metrics:
#     runs-on: ubuntu-latest
#     environment: 
#       name: production
#     permissions:
#       contents: write
#     steps:
#       - uses: oitimon/metrics@366f8b9dfe3a59656c67d5dcad9950f59c9bc96d
#         with:
#           token: ${{ secrets.METRICS_TOKEN }}
